# Generated by Django 5.0.6 on 2024-05-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created time'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(upload_to='services', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='service',
            name='updated',
            field=models.DateField(auto_now=True, verbose_name='Updated time'),
        ),
    ]
