# Generated by Django 5.0.6 on 2024-05-28 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100, unique=True, verbose_name='Key name')),
                ('name', models.CharField(max_length=50, verbose_name='Social network')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Link')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('updated', models.DateField(auto_now=True, verbose_name='Updated time')),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
                'ordering': ['name'],
            },
        ),
    ]
