# Generated by Django 5.0.6 on 2024-05-29 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('content', models.TextField(max_length=200, verbose_name='Content')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('updated', models.DateField(auto_now=True, verbose_name='Updated time')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ['title'],
            },
        ),
    ]
